server:
  port: 1101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: gateway
  profiles:
    active: h2
  data:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION






