server:
  port: 1101
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

app:
  jwt:
    secret: abcdefghijklmnOPQRSTUVWXYZ

spring:
  application:
    name: gateway
  profiles:
    active: h2
  data:
    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
#Use your own Redis configuration.
  redis:
    database: '0'
    password: 123456
    host: 127.0.0.1
    port: '6379'
    pool:
      max-wait: '-1'
      max-active: '200'
      max-idle: '10'
      min-idle: '0'
    timeout: '1000'
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins: "*"
            allowed-headers: "*"
            allowed-methods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTION






