spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:securityDemo;MODE=MySQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
  sql:
    init:
      schema-locations: classpath:sql/schema.sql
      data-locations: classpath:sql/data.sql
      mode: embedded
    h2:
      console:
        enabled: true
        settings:
          trace: true
          web-allow-others: true
        path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none